# This file stores the flash_commands for each mcus
# Previous version KCONFIG_CONFIG was needed now it is automaticly added when make flash is called
# version : 0.2
# tested/supported flash methods :
#  - make flash
#  - sdcard_flash
#  - flashtool.py
#  - mount/cp/umount (for rp2040)
#  - external scripts ...

#[cartographer]
#klipper_section: mcu scanner
#is_klipper_fw: false
#action_command: git -C ~/cartographer_firmware pull
#action_command: ~/cartographer_firmware/fw_update.sh

#[rpi]
#klipper_section: mcu rpi
#action_command: make flash

#[Octopus]
#klipper_section: mcu
#action_command: make flash /dev/serial/by-id/usb-Klipper_stm32f446xx_<BOARD_ID>-if00
#quiet_command: enter_bootloader -u <YOUR_CANBUS_UUID>
#action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32f446xx_<BOARD_ID>-if00

#[EBB36]
#klipper_section: mcu toolhead
#action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 2fc4afec81e3  

#[nevermore]
#klipper_section: mcu nevermore
#action_command: make flash FLASH_DEVICE=/dev/serial/by-id/usb-Klipper_rp2040_<your_id_here>-if00

#[beacon]
#is_klipper_fw: false
#quiet_command: sudo systemctl stop klipper
#action_command: git -C ~/beacon_klipper pull
#action_command: ~/beacon_klipper/update_firmware.py update all
